str = 'Firstbit Solutions'

#print(str.capitalize())
#print(str.count('Bit))
#print(str.endswith('ions'))
#print(str.find('bit))
#print(str.index('Bit'))
#print(str.isalnum())
#print(str.isalpha())
#print(str.isdigit())
#print(str.islower())
#print(str.isspace())
#print(str.isupper())
#data = ', '.join(['101' , 'ABC' , 'IT'])
#print(data)
#print(str.lower())
#print(str.replace('Bit', 'Byte'))
#str = '     [Firstbit solutions]   '
#print(str.strip(' []'))
#print(str.swapcase())
#print(str.title())
print(str.upper())