import tkinter as tk
root=tk.Tk()
root.title("This is my app")
root.geometry('400x500')
l1 = tk.Label(root,text="left",font=("Goudy Stout",20),bg = "Pink", fg = "white").grid(row=0,column=1)
l2 = tk.Label(root,text="right",font=("Goudy Stout",20),bg = "Green", fg = "white").place(x=12,y=67)
# # l3 = tk.Label(root,text="top",font=("Goudy Stout",20),bg = "Brown", fg = "white")
# # l4 = tk.Label(root,text="bottom",font=("Goudy Stout",20),bg = "yellow", fg = "white")
# l1.pack(side="left")
# l2.pack(side="right")
# #  l3.pack(side="top")
# #  l4.pack(side="bottom")
# e=tk.Entry(root)
# e.pack()
# def show():
#     print(e.get())
# btn=tk.Button(root,text="saee",command=show)
# btn.pack()
root.mainloop()